/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type PromptCategory = { 'cgiAds' : null } |
  { 'marketing' : null } |
  { 'design' : null } |
  { 'photoGeneration' : null } |
  { 'business' : null } |
  { 'socialMedia' : null } |
  { 'videoGeneration' : null } |
  { 'storytelling' : null };
export interface PromptRecord {
  'id' : bigint,
  'title' : string,
  'isPremium' : boolean,
  'tags' : Array<string>,
  'description' : string,
  'fullText' : string,
  'isPopular' : boolean,
  'category' : PromptCategory,
  'isNew' : boolean,
}
export interface UserProfile {
  'hasPremiumMembership' : boolean,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<[string, string, string], bigint>,
  'addPrompt' : ActorMethod<[PromptRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllPrompts' : ActorMethod<[], Array<PromptRecord>>,
  'getBlogPost' : ActorMethod<[bigint], BlogPost>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getFavoritePrompts' : ActorMethod<[], Array<PromptRecord>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<string>>,
  'getPrompt' : ActorMethod<[bigint], PromptRecord>,
  'getPromptsByCategory' : ActorMethod<[PromptCategory], Array<PromptRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
  'toggleFavoritePrompt' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];