/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PromptCategory = IDL.Variant({
  'cgiAds' : IDL.Null,
  'marketing' : IDL.Null,
  'design' : IDL.Null,
  'photoGeneration' : IDL.Null,
  'business' : IDL.Null,
  'socialMedia' : IDL.Null,
  'videoGeneration' : IDL.Null,
  'storytelling' : IDL.Null,
});
export const PromptRecord = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPremium' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'fullText' : IDL.Text,
  'isPopular' : IDL.Bool,
  'category' : PromptCategory,
  'isNew' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'hasPremiumMembership' : IDL.Bool,
  'name' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPrompt' : IDL.Func([PromptRecord], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllPrompts' : IDL.Func([], [IDL.Vec(PromptRecord)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getFavoritePrompts' : IDL.Func([], [IDL.Vec(PromptRecord)], ['query']),
  'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPrompt' : IDL.Func([IDL.Nat], [PromptRecord], ['query']),
  'getPromptsByCategory' : IDL.Func(
      [PromptCategory],
      [IDL.Vec(PromptRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  'toggleFavoritePrompt' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PromptCategory = IDL.Variant({
    'cgiAds' : IDL.Null,
    'marketing' : IDL.Null,
    'design' : IDL.Null,
    'photoGeneration' : IDL.Null,
    'business' : IDL.Null,
    'socialMedia' : IDL.Null,
    'videoGeneration' : IDL.Null,
    'storytelling' : IDL.Null,
  });
  const PromptRecord = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPremium' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'fullText' : IDL.Text,
    'isPopular' : IDL.Bool,
    'category' : PromptCategory,
    'isNew' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'hasPremiumMembership' : IDL.Bool,
    'name' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addPrompt' : IDL.Func([PromptRecord], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllPrompts' : IDL.Func([], [IDL.Vec(PromptRecord)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getFavoritePrompts' : IDL.Func([], [IDL.Vec(PromptRecord)], ['query']),
    'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPrompt' : IDL.Func([IDL.Nat], [PromptRecord], ['query']),
    'getPromptsByCategory' : IDL.Func(
        [PromptCategory],
        [IDL.Vec(PromptRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
    'toggleFavoritePrompt' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };